#!/usr/bin/env python3
"""
Home Assistant OS Add-on entry point for MQTT to Cognite Data Fusion extractor.
This script reads the configuration file generated by run.sh and starts the extractor.
"""

import sys
import os

# Add the current directory to Python path so we can import mqtt_extractor
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import and run the main extractor
from mqtt_extractor.main import main

if __name__ == "__main__":
    # The config file path is passed as the first argument from run.sh
    if len(sys.argv) < 2:
        print("Error: Config file path required", file=sys.stderr)
        sys.exit(1)
    
    main()

